### ISSUE TITLE
Named parameters implementation

### ISSUE THREAD

**Issue by mlafon** [flightaware/Tcl-bounties#13]
I have started working on this item and have submited an initial TIP draft.

**Comment by bovine** [comment]
Although he did not yet attempt to integrate the syntax natively into the proc command, coordinating with @cyanogilvie (Cyan Ogilvie) to use his Tcl Conference presentation implementation might be an efficient solution:  https://www.tcl.tk/community/tcl2016/abstracts.html#T33

**Comment by mlafon** [comment]
I will look at the presentation but I think that trying to use the "-argname arg" syntax may have unexpected results with procedures which may use a similar syntax for other means.

My proposal is to use a dedicated syntax (one which is not valid in current Tcl version) for named arguments. For example:
`myproc "some pos arg" {color}=green {pos}={5 5}`

**Comment by cyanogilvie** [comment]
Hi

There is a TIP in progress for the parse_args system too.  If it does land
in the core it will probably go through some design revisions first, but I
think whatever does go in should strive to align with the patterns already
used by the language.

Cyan

**Comment by bll123** [comment]
That syntax doesn't parse: 
```
% puts {pos}={5 5}
extra characters after close-brace
```
and
```
set x color=green
[myproc $x ...]
```
will break.

I think, somehow, an indicator will need to be passed to indicate that named parameters are in use.

**Idea 1:**
```
proc { fh data } { puts $fh $data }
[myproc --np -fh $outfh -data $data]
# with positional and named parameters:
[myproc $outfh --np -data $data]
```

Not very elegant, but it works.

**Idea 2:**
```
[np myproc -fh $outfh -data $data]
```

Can't mix positional and named parameters with this one.  

**Idea 3:**
```
proc -np myproc { fh data } { puts $fh $data }
[myproc -fh $outfh -data $data]
[myproc $outfh -data $data]
```

This doesn't break backwards compatibility, but requires changing the target procedures.
This has some flexibility in that procedures that already use -parameters can be left alone.
Positional and named parameters could be mixed.

**Idea 4:**
```
# pragma doesn't exist, but would be easy to implement.
pragma namedparameters  ; # default is nonamedparameters for backwards compatibility
# once this pragma is turned on, all procs can use named parameter parsing.
[myproc -fh $outfh -data $data]
[myproc $outfh $data]
```

Some people will hate this idea, but pragmas are useful for turning on new features that would break backwards compatibility.  And eventually, after time, the default can be changed.

I would collect some ideas from other people, see what works best.

> I will look at the presentation but I think that trying to use the "-argname arg" syntax may have unexpected results with procedures which may use a similar syntax for other means.

And of course, it can be implemented this way, but it would probably have to wait for the 9.0 release, as, as you noted, it would break any procedure using -parameters.

**Comment by mlafon** [comment]
Thanks for all the feedback.

> That syntax doesn't parse:
> extra characters after close-brace

Yes, that is exactly why I have chosen this syntax: it is currently not allowed by the Tcl parser. The proposed modification will require changes in the parser, but:

- we're 100% sure to not break any existing program
- it is possible to only allow this format for commands which can handle named arguments (at least all Tcl commands defined using the proc command)
- no modification is required in existing proc definition (useful for calling proc from external packages)

I will add all suggestions I have received in the TIP once the initial version will be published, so that we can discuss them an receive feedback from other Tcl core members.

**Comment by chpock** [comment]
My implementation of issues "Named parameters" & "Call-by-name syntactic sugar for proc definitions" is here: https://github.com/chpock/ckl/blob/master/procarg/procarg.tcl It's use "args" argument and "default argument value". Doesn't break compatibility, just add a little sugar.

The proc definition will looks like:
```tcl
proc geturl { url &data { args {
  {0 string  -allowempty false}
  {-query       dict    -nodefault}
  {-callback    string  -nodefault -allowempty false}
  {-timeout     int     -default 60000}
  {-headers     dict    -nodefault}
  {-strict      boolean -default true}
  {-checkonline switch}
  {-proxytag    string  -nodefault}
  {-useragent   string  -nodefault}
  {-accept      string  -nodefault}
}}} {
  #.. code here ...
  puts "timeout: $opts(-timeout)"
  set data "!!! OUTPUT DATA !!!"
  return true
}
geturl "http://example.com" data -callback ::testcallback
puts $data
```

**Comment by mlafon** [comment]
Initial draft of TIP457 has been published : http://purl.org/tcl/tip/457.html

**Comment by mlafon** [comment]
After Tcl-community feedback, the [TIP #457](http://www.tcl.tk/cgi-bin/tct/tip/457.html) has been updated. The current proposal is to use a dedicated 'call' builtin command to handle named parameters, using an "-option value" syntax.

The implementation is currently available in [mlafon/tcl:457-CALL-CMD](https://github.com/mlafon/tcl/tree/457-CALL-CMD).

Can you tell me if the current TIP/implementation is what you expect for this bounty?

**Comment by mlafon** [comment]
@bovine, have you looked at my current proposal to know if this match what you expect for this bounty?

Thanks for any feedback.

**Comment by bovine** [comment]
I'm not particularly fond of the "call" notation and I suspect that requirement will end up leading to fewer users learning about it or wanting to write code that uses a syntax that is so radically different.  However, I'm not the decision maker and @lehenbauer is ultimately the one who will be awarding the bounties.

**Comment by mlafon** [comment]
In case "radically different" is related to my initial proposal, it has since been abandoned. The current proposal is probably more intuitive (by using the "-option value" syntax) but you're right that users must know about the command first.

Example:
`call -opts myproc -color green -pos {5 5} -- posArg`

**Comment by bll123** [comment]
There is one more possibility that could be used.

A setup procedure is called.  This only needs to be run once.
`     setupnamedparameters myproc -rename`
Internally, this could do:
```
     rename myproc _real_myproc
     set argnames [info args _real_myproc]
     ...
     # create a new procedure with the old name that accepts named arguments
     proc myproc { args } {
           # do named arguments processing 
           ...
           # this would need the appropriate uplevel, of course
           _real_myproc {*}$arglist
     }
```
Now just call myproc as usual, or with named parameters.

Since renaming procedures in external packages isn't going to work, a way to specify the new procedure name should also be present.
`     setupnamedparameters ::extpkg::myproc extpkg_myproc`
and then call the new procedure...
`     extpkg_myproc -c cvalue`
etc.

**Comment by resuna** [comment]
A central part of the Tcl bounty for named parameters is to produce a solution that encourages people to use named parameters. It needs to be something that fits well into existing Tcl usage, without a lot of boilerplate exposed to the caller or implementer.

That's a key purpose of the requirement that named parameters don't require changes to the definition of the proc. But the flip side is just as important... calling a proc using named parameters should seem natural and as similar as possible to the way existing named parameters are used.

And that's a problem, because TIP #457 unfortunately does not describe something that is likely to have a high uptake among Tcl developers. It makes the process of calling a proc with named parameters verbose, which will tend to discourage its use.

So... some additional points to bear in mind: 

1.	There's really no need for a huge amount of flexibility in the "new syntax". Either existing positional style, or the new named style using the information provided in the proc definition, are the only alternatives needed. Extensions like the one implied by `"call -opts -npos 1"`  are really kind of overkill.
2.	On the other hand, some kind of flag on the call of a proc is ok, and is probably required, but it needs to be something that doesn't create a heavy cognitive load on the caller.
3.	Finally, and importantly, there's really already enough information provided in existing proc definitions to unambiguously define a viable new behavior for any proc that currently uses optional positional parameters.

So, by point 2, let's say we have a flag on the call or any proc: if the proc name is preceded by a "-" and the same proc name with the "dash" included doesn't already exist, then the call will be made with the named parameter syntax:

Using this example proc:

```
proc foo {bar {opt1 ""} {opt2 ""} args} {
	puts [list called foo bar= $bar opt1= $opt1 opt2= $opt2 args= $args]
}
```

This provides enough information for any call using named arguments:

```
[foo zot b] -> "called foo bar= zot opt1= b opt2= {} args= {}"
[-foo zot b] -> "called foo bar= zot opt1= {} opt2= {} args= b"
[foo zot -opt2 b] -> "called foo bar= zot opt1= -opt2 opt2= b args= {}"
[-foo zot -opt2 b] -> "called foo bar= zot opt1= {} opt2= b args= {}"
```

The use of "-" as a sentinel is not the only possible syntax, of course, but it's one that would be immediately recognizable. One could call "*foo" or "@foo" or even "{-}foo" to make completely sure there's no chance of naming conflict.

In addition, it would be OK to have something to flag a proc as always taking the new syntax. For example:

```
proc -named-parameters foo {bar {opt1 ""} {opt2 ""} args} { ... }

nproc foo {bar {opt1 ""} {opt2 ""} args} { ... }
```

Or even:

`-proc foo {bar {opt1 ""} {opt2 ""} args} { ... }`

Though that may be too "cute".

Regardless of the exact syntax, a proc defined this way wouldn't even allow positional parameters for arguments with a default value. 

```
[foo zot b] -> "called foo bar= zot opt1= {} opt2= {} args= b"
[-foo zot b] -> "called foo bar= zot opt1= {} opt2= {} args= b"
[foo zot -opt2 b] -> "called foo bar= zot opt1= {} opt2= b args= {}"
[-foo zot -opt2 b] -> "called foo bar= zot opt1= {} opt2= b args= {}"
```

The suggestion by bll123 for a one-time call to enable named parameters would be an additional level of safety, though it would have to be implemented as a first-class feature rather than a wrapper.  It would allow for the unlikely situation where existing code has separate procs named both "foo" and "-foo" BUT there's a "bar" but no "-bar" AND there's code that depends on "-bar" failing...

**Comment by resuna** [comment]
Updates based on the discussion on the Tcl core list:

We're dropping the requirements that existing procs with optional vars be callable this way, so we don't need anything special on the caller side. You'd just call "new style" procs with named parameters instead of positional parameters.

Declaration syntax that extends the positional parameters syntax is acceptable, eg:

```
proc foo {bar {opt1 "" -opt1} {opt2 "" -opt2} args} { ... }

foo zot -opt1 a  -> "called foo bar= zot opt1= a opt2= {} args= {}"
foo zot -opt1 x y -> "called foo bar= zot opt1= x opt2= {} args= y"
```

**Comment by mlafon** [comment]
I have already started to work on a similar solution and will provide an updated TIP shortly.

Thanks for the clarification about the bounty requirement.

My new proposal will provide options on arguments specification to add support for : named parameters, type checking, flag parameters, help description and pass-by-name (upvar) handling.

For example:
`
proc foo {bar {opt1 "" -name -opt1 -help "This is opt1 description"} {opt2 "" -name -opt2 -type int} args} { ... }
`

Is this something that can match your requirements?

**Comment by resuna** [comment]
Named parameters are no longer part of the bounty program.
