### ISSUE TITLE
I noticed that ActiveState Tcl doesn't support '\b' in regex??  

### ISSUE THREAD

**Issue by wm2015email** [flightaware/Tcl-bounties#41]
I noticed that ActiveState Tcl doesn't support '\b' in regex??  seems like kind of a bug?   

Incidently there was soemthing else strange i was seeing in activeState TCL,   they were finding curly braces in the comments and giving unbalanced paren error.

It this is an unsupport version of TCL i think they should warn people not to use it on their website?

**Comment by resuna** [comment]
First, this project doesn't have anything to do with ActiveState, so you'll have to repeat this question on their site.

Three notes, that might be helpful:

1. [info tclversion] will tell you what version of tcl you're using.

2. Escapes are part of Advanced Regular Expression syntax, they have no effect in Basic (traditional) REs or Extended (equivalent to Henry Spencer's syntax) REs.If your RE is enclosed in doublequotes this doesn't matter because doublequoted strings will already have had escapes converted before regexp sees them.

3. All versions of Tcl see curly braces in comments, because comments are not part of list or string syntax, in fact comments only have an effect if they're seen at a place where a command can appear, and only when parsed as commands.
